export const SET_DOC_DATA = "SET_DOC_DATA";
export const SET_DBOTS = "SET_DBOTS";
export const SET_COUNT = "SET_COUNT";
export const SET_CURRENT = "SET_CURRENT";
export const SET_ADDRESS = "SET_ADDRESS";
export const SET_DETAIL_DATA = "SET_DETAIL_DATA";
export const SET_STATE_CHANNEL_STATUS = "SET_STATE_CHANNEL_STATUS";
export const SET_STATE_CHANNEL_BANLANCE = "SET_STATE_CHANNEL_BANLANCE";
