export const SET_DOC_DATA = "SET_DOC_DATA";
export const SET_DBOTS = "SET_DBOTS";
export const SET_COUNT = "SET_COUNT";
export const SET_CURRENT = "SET_CURRENT";
export const SET_QUERYING = "SET_QUERYING";
export const SET_ADDRESS = "SET_ADDRESS";
export const SET_DETAIL_DATA = "SET_DETAIL_DATA";
export const SET_STATE_CHANNEL_STATUS = "SET_STATE_CHANNEL_STATUS";
export const SET_STATE_CHANNEL_BANLANCE = "SET_STATE_CHANNEL_BANLANCE";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_CURRENT_SUB_MENU = "SET_CURRENT_SUB_MENU";
export const SET_CURRENT_ITEM_NAME = "SET_CURRENT_ITEM_NAME";
export const SET_SORT_TYPE = "SET_SORT_TYPE";
export const SET_SORT_DIR = "SET_SORT_DIR";

export const SET_CURRENT_COMMENTS = "SET_CURRENT_COMMENTS";
export const SET_CURRENT_COMMENTS_PAGE = "SET_CURRENT_COMMENTS_PAGE";
export const SET_CURRENT_COMMENTS_COUNT = "SET_CURRENT_COMMENTS_COUNT";
